Dependency resolution
fasten-project/fasten-pypi-plugin pull request #25
Opened 2022-06-22 17:18 UTC by michelescarlato

Please merge.

LGTM.

2022-06-22 19:47 UTC, amphioxis requested changes

2022-06-22 19:47 UTC, amphioxis commented on src/fasten/executePypiResolver.py
> +            time.sleep(20)
Here is the other timer. I guess this whole if statement can be removed?

2022-06-23 08:48 UTC, michelescarlato commented on src/fasten/__main__.py
> +    time.sleep(20)
It is necessary.

The timer sometimes is neither fixing an issue that arises.
The issue is:
"It seems that at the first execution even though the req_dep_resolved.txt has been created, it cannot be found by the function at line 41 (readRequirementsFile)".

2022-06-23 08:48 UTC, michelescarlato commented on src/fasten/executePypiResolver.py
> +            time.sleep(20)
Nope. This timer is required.
The if statement also.

2022-06-23 08:50 UTC, merged